export const DEFAULT_SPREADSHEET_LOCALE = "esES";

export const univerPtBrLocale = {
  design: {
    Confirm: { cancel: "Cancelar", confirm: "OK" },
    CascaderList: { empty: "Nenhum" },
    Calendar: {
      year: "",
      weekDays: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
      months: [
        "Janeiro",
        "Fevereiro",
        "Março",
        "Abril",
        "Maio",
        "Junho",
        "Julho",
        "Agosto",
        "Setembro",
        "Outubro",
        "Novembro",
        "Dezembro",
      ],
    },
    Select: { empty: "Nenhum" },
    ColorPicker: {
      more: "Mais cores",
      cancel: "Cancelar",
      confirm: "OK",
    },
  },
  toolbar: {
    undo: "Desfazer",
    redo: "Refazer",
    font: "Fonte",
    fontSize: "Tamanho da fonte",
    bold: "Negrito",
    italic: "Itálico",
    strikethrough: "Tachado",
    subscript: "Subscrito",
    superscript: "Sobrescrito",
    underline: "Sublinhado",
    textColor: { main: "Cor do texto", right: "Escolher cor" },
    fillColor: { main: "Cor de preenchimento", right: "Escolher cor" },
    table: {
      main: "Tabela",
      insert: "Inserir tabela",
      colCount: "Quantidade de colunas",
      rowCount: "Quantidade de linhas",
    },
    resetColor: "Redefinir",
    order: "Lista ordenada",
    unorder: "Lista não ordenada",
    checklist: "Lista de tarefas",
    documentFlavor: "Modo moderno",
    alignLeft: "Alinhar à esquerda",
    alignCenter: "Centralizar",
    alignRight: "Alinhar à direita",
    alignJustify: "Justificar",
    horizontalLine: "Linha horizontal",
    headerFooter: "Cabeçalho e rodapé",
    pageSetup: "Configurar página",
    formatPainter: "Pincel de formatação",
    border: { main: "Bordas", right: "Estilo da borda" },
    mergeCell: { main: "Mesclar células", right: "Escolher tipo de mesclagem" },
    horizontalAlignMode: { main: "Alinhamento horizontal", right: "Alinhamento" },
    verticalAlignMode: { main: "Alinhamento vertical", right: "Alinhamento" },
    textWrapMode: { main: "Quebra de texto", right: "Modo de quebra" },
    textRotateMode: { main: "Rotação do texto", right: "Modo de rotação" },
    more: "Mais",
    toggleGridlines: "Mostrar/ocultar grades",
    heading: {
      "1": "Título 1",
      "2": "Título 2",
      "3": "Título 3",
      "4": "Título 4",
      "5": "Título 5",
      "6": "Título 6",
      normal: "Normal",
      title: "Título",
      subTitle: "Subtítulo",
      tooltip: "Definir título",
    },
  },
  rightClick: {
    copy: "Copiar",
    cut: "Recortar",
    paste: "Colar",
    delete: "Excluir",
    pasteSpecial: "Colagem especial",
    pasteValue: "Colar valores",
    pasteFormat: "Colar formatação",
    pasteColWidth: "Colar largura da coluna",
    insert: "Inserir",
    insertRow: "Inserir linha",
    insertColumn: "Inserir coluna",
    deleteCell: "Excluir célula",
    insertCell: "Inserir célula",
    deleteSelectedRow: "Excluir linha selecionada",
    deleteSelectedColumn: "Excluir coluna selecionada",
    rowHeight: "Altura da linha",
    columnWidth: "Largura da coluna",
    clearSelection: "Limpar",
    clearContent: "Limpar conteúdo",
    clearFormat: "Limpar formatação",
    clearAll: "Limpar tudo",
    hide: "Ocultar",
    showHide: "Mostrar ocultos",
    freeze: "Congelar",
    freezeCol: "Congelar até esta coluna",
    freezeRow: "Congelar até esta linha",
    cancelFreeze: "Desfazer congelamento",
    protectRange: "Proteger linhas e colunas",
    editProtectRange: "Definir intervalo protegido",
    removeProtectRange: "Remover intervalo protegido",
    turnOnProtectRange: "Adicionar intervalo protegido",
    viewAllProtectArea: "Ver todas as áreas protegidas",
  },
  sheets: {
    tabs: { sheetCopy: "(Cópia{0})", sheet: "Planilha" },
    info: {
      overlappingSelections: "Não é possível usar esse comando em seleções sobrepostas",
      acrossMergedCell: "Atravessa uma célula mesclada",
      partOfCell: "Apenas parte de uma célula mesclada foi selecionada",
      hideSheet: "Não haverá planilha visível após ocultar esta",
    },
  },
  formula: {
    progress: {
      analyzing: "Analisando",
      calculating: "Calculando",
      "array-analysis": "Analisando matriz",
      "array-calculation": "Calculando matriz",
      done: "Concluído",
    },
    insert: {
      tooltip: "Funções",
      more: "Mais funções...",
    },
    prompt: {
      helpExample: "EXEMPLO",
      helpAbstract: "SOBRE",
      required: "Obrigatório.",
      optional: "Opcional.",
    },
    error: {
      title: "Erro",
      divByZero: "Erro de divisão por zero",
      name: "Erro de nome inválido",
      value: "Erro no valor",
      num: "Erro numérico",
      na: "Valor indisponível",
      cycle: "Erro de referência circular",
      ref: "Erro de referência de célula inválida",
      spill: "A área de expansão não está vazia",
      calc: "Erro de cálculo",
      error: "Erro",
      connect: "Obtendo dados",
      null: "Erro nulo",
    },
    functionType: {
      financial: "Financeiro",
      date: "Data e hora",
      math: "Matemática e trigonometria",
      statistical: "Estatística",
      lookup: "Pesquisa e referência",
      database: "Banco de dados",
      text: "Texto",
      logical: "Lógica",
      information: "Informação",
      engineering: "Engenharia",
      cube: "Cubo",
      compatibility: "Compatibilidade",
      web: "Web",
      array: "Matriz",
      univer: "Univer",
      user: "Definida pelo usuário",
      definedname: "Nome definido",
    },
    moreFunctions: {
      confirm: "Confirmar",
      prev: "Anterior",
      next: "Próxima",
      searchFunctionPlaceholder: "Buscar função",
      allFunctions: "Todas as funções",
      syntax: "SINTAXE",
    },
    operation: { pasteFormula: "Colar fórmula" },
  },
  shortcut: {
    undo: "Desfazer",
    redo: "Refazer",
    cut: "Recortar",
    copy: "Copiar",
    paste: "Colar",
    "shortcut-panel": "Alternar painel de atalhos",
  },
  sheet: {
    numfmt: {
      title: "Formato numérico",
      numfmtType: "Tipos de formato",
      cancel: "Cancelar",
      confirm: "Confirmar",
      general: "Geral",
      accounting: "Contábil",
      text: "Texto",
      number: "Número",
      percent: "Porcentagem",
      scientific: "Científico",
      currency: "Moeda",
      date: "Data",
      time: "Hora",
      thousandthPercentile: "Separador de milhar",
      preview: "Visualização",
      dateTime: "Data e hora",
      decimalLength: "Casas decimais",
      currencyType: "Símbolo da moeda",
      moreFmt: "Formatos",
      financialValue: "Valor financeiro",
      roundingCurrency: "Arredondamento de moeda",
      timeDuration: "Duração",
      currencyDes:
        "O formato de moeda é usado para representar valores monetários. O formato contábil alinha uma coluna de valores pelos pontos decimais.",
      accountingDes:
        "O formato contábil alinha uma coluna de valores com símbolos monetários e pontos decimais.",
      dateType: "Tipo de data",
      dateDes:
        "O formato de data apresenta valores de séries de data e hora como datas.",
      negType: "Tipo de número negativo",
      generalDes: "O formato geral não contém um formato numérico específico.",
      thousandthPercentileDes:
        "O formato com separador de milhar é usado para números comuns. Os formatos monetário e contábil trazem opções especializadas para valores financeiros.",
      addDecimal: "Aumentar casas decimais",
      subtractDecimal: "Diminuir casas decimais",
      customFormat: "Formato personalizado",
      customFormatDes:
        "Crie formatos numéricos personalizados com base em formatos existentes.",
    },
  },
  spreadsheetLabel: "Planilha",
  spreadsheetRightLabel: "mais planilhas",
  align: {
    left: "esquerda",
    center: "centro",
    right: "direita",
    top: "topo",
    middle: "meio",
    bottom: "base",
  },
  button: {
    confirm: "OK",
    cancel: "Cancelar",
    close: "Fechar",
    update: "Atualizar",
    delete: "Excluir",
    insert: "Inserir",
    prevPage: "Anterior",
    nextPage: "Próxima",
    total: "total:",
  },
  punctuation: {
    tab: "Tab",
    semicolon: "ponto e vírgula",
    comma: "vírgula",
    space: "espaço",
  },
  colorPicker: {
    collapse: "Recolher",
    customColor: "PERSONALIZADA",
    change: "Alterar",
    confirmColor: "OK",
    cancelColor: "Cancelar",
  },
  borderLine: {
    borderTop: "borda superior",
    borderBottom: "borda inferior",
    borderLeft: "borda esquerda",
    borderRight: "borda direita",
    borderNone: "sem borda",
    borderAll: "todas as bordas",
    borderOutside: "bordas externas",
    borderInside: "bordas internas",
    borderHorizontal: "bordas horizontais",
    borderVertical: "bordas verticais",
    borderColor: "cor da borda",
    borderSize: "espessura da borda",
    borderType: "tipo de borda",
  },
  merge: {
    all: "Mesclar tudo",
    vertical: "Mesclar verticalmente",
    horizontal: "Mesclar horizontalmente",
    cancel: "Desfazer mesclagem",
    overlappingError: "Não é possível mesclar áreas sobrepostas",
    partiallyError: "Não é possível executar esta operação em células parcialmente mescladas",
    confirm: {
      title:
        "Continuar a mesclagem manterá apenas o valor da célula superior esquerda e descartará os demais. Deseja continuar?",
      cancel: "Cancelar mesclagem",
      confirm: "Continuar mesclagem",
      warning: "Aviso",
      dismantleMergeCellWarning:
        "Isso fará com que algumas células mescladas sejam desfeitas. Deseja continuar?",
    },
  },
  filter: {
    confirm: {
      error: "Houve um problema",
      notAllowedToInsertRange:
        "Não é permitido mover células para cá enquanto houver um filtro ativo",
    },
  },
  textWrap: { overflow: "Transbordar", wrap: "Quebrar", clip: "Cortar" },
  textRotate: {
    none: "Nenhuma",
    angleUp: "Inclinar para cima",
    angleDown: "Inclinar para baixo",
    vertical: "Empilhar verticalmente",
    rotationUp: "Rotacionar para cima",
    rotationDown: "Rotacionar para baixo",
  },
  sheetConfig: {
    delete: "Excluir",
    copy: "Duplicar",
    rename: "Renomear",
    changeColor: "Alterar cor",
    hide: "Ocultar",
    unhide: "Mostrar",
    moveLeft: "Mover para a esquerda",
    moveRight: "Mover para a direita",
    resetColor: "Redefinir cor",
    cancelText: "Cancelar",
    chooseText: "Confirmar cor",
    tipNameRepeat: "O nome da aba não pode se repetir. Ajuste o nome.",
    noMoreSheet:
      "A pasta de trabalho precisa ter ao menos uma planilha visível. Para excluir a atual, insira uma nova planilha ou exiba uma oculta.",
    confirmDelete: "Tem certeza que deseja excluir",
    redoDelete: "É possível desfazer com Ctrl+Z",
    noHide: "Não é possível ocultar, mantenha ao menos uma aba visível",
    chartEditNoOpt: "Esta operação não é permitida no modo de edição de gráfico",
    sheetNameErrorTitle: "Houve um problema",
    sheetNameSpecCharError:
      "O nome não pode exceder 31 caracteres, não pode começar ou terminar com ' e não pode conter: [ ] : \\ ? * /",
    sheetNameCannotIsEmptyError: "O nome da planilha não pode estar vazio.",
    sheetNameAlreadyExistsError: "O nome da planilha já existe. Informe outro nome.",
    deleteSheet: "Excluir planilha",
    deleteSheetContent:
      "Confirma a exclusão desta planilha? Ela não poderá ser recuperada depois.",
    addProtectSheet: "Proteger planilha",
    removeProtectSheet: "Desproteger planilha",
    changeSheetPermission: "Alterar permissões da planilha",
    viewAllProtectArea: "Ver todas as áreas protegidas",
  },
  info: {
    tooltip: "Dica",
    error: "Erro",
    notChangeMerge: "Não é possível alterar parcialmente células mescladas",
    detailUpdate: "Nova versão aberta",
    detailSave: "Cache local restaurado",
    loading: "Carregando...",
    copy: "Copiar",
    return: "Sair",
    rename: "Renomear",
    tips: "Renomear",
    noName: "Planilha sem título",
    wait: "aguardando atualização",
    add: "Adicionar",
    addLast: "mais linhas na parte inferior",
    backTop: "Voltar ao topo",
    pageInfo: "Total ${total}, ${totalPage} páginas, atual ${currentPage}",
    nextPage: "Próxima",
    tipInputNumber: "Digite um número",
    tipInputNumberLimit: "O aumento permitido está limitado a 1-100",
    tipRowHeightLimit: "A altura da linha deve estar entre 0 e 545",
    tipColumnWidthLimit: "A largura da coluna deve estar entre 0 e 2038",
    pageInfoFull: "Total ${total}, ${totalPage} páginas, todos os dados exibidos",
    problem: "Houve um problema",
    forceStringInfo: "Número armazenado como texto",
  },
  clipboard: {
    paste: {
      exceedMaxCells: "A quantidade de células coladas excede o máximo permitido",
      overlappingMergedCells: "A área de colagem se sobrepõe a células mescladas",
    },
    shortCutNotify: {
      title: "Cole usando atalhos de teclado.",
      useShortCutInstead: "Conteúdo do Excel detectado. Use o atalho de teclado para colar.",
    },
    authentication: {
      title: "Permissão negada",
      content: "Permita que o Univer acesse sua área de transferência.",
    },
  },
  statusbar: {
    sum: "Soma",
    average: "Média",
    min: "Mín",
    max: "Máx",
    count: "Contagem numérica",
    countA: "Contagem",
    clickToCopy: "Clique para copiar",
    copied: "Copiado",
  },
  autoFill: {
    copy: "Copiar célula",
    series: "Preencher série",
    formatOnly: "Somente formato",
    noFormat: "Sem formato",
  },
  rangeSelector: {
    placeholder: "Selecione um intervalo ou informe um valor",
    tooltip: "Selecionar intervalo",
    title: "Selecionar um intervalo de dados",
    addAnotherRange: "Adicionar intervalo",
    buttonTooltip: "Selecionar intervalo de dados",
    placeHolder: "Selecione um intervalo ou digite.",
    confirm: "Confirmar",
    cancel: "Cancelar",
  },
  "sheet-view": "Visualização da planilha",
  "sheet-edit": "Edição da planilha",
  definedName: {
    managerTitle: "Gerenciar nomes",
    managerDescription:
      "Crie um nome definido selecionando células ou fórmulas e informando o nome desejado.",
    addButton: "Adicionar nome definido",
    featureTitle: "Nomes definidos",
    ratioRange: "Intervalo",
    ratioFormula: "Fórmula",
    confirm: "Confirmar",
    cancel: "Cancelar",
    scopeWorkbook: "Pasta de trabalho",
    inputNamePlaceholder: "Digite um nome (sem espaços)",
    inputCommentPlaceholder: "Digite um comentário",
    inputRangePlaceholder: "Digite um intervalo (sem espaços)",
    inputFormulaPlaceholder: "Digite uma fórmula (sem espaços)",
    nameEmpty: "O nome não pode estar vazio",
    nameDuplicate: "O nome já existe",
    formulaOrRefStringEmpty: "A fórmula ou referência não pode estar vazia",
    formulaOrRefStringInvalid: "Fórmula ou referência inválida",
    defaultName: "NomeDefinido",
    updateButton: "Atualizar",
    deleteButton: "Excluir",
    deleteConfirmText: "Tem certeza que deseja excluir este nome definido?",
    nameConflict: "O nome entra em conflito com o nome de uma função",
    nameInvalid: "O nome é inválido",
    nameSheetConflict: "O nome entra em conflito com o nome da planilha",
  },
  uploadLoading: { loading: "Carregando..., restante", error: "Erro" },
  ribbon: {
    start: "Início",
    startDesc: "Inicie a planilha e ajuste parâmetros básicos.",
    insert: "Inserir",
    insertDesc: "Insira linhas, colunas, gráficos e outros elementos.",
    formulas: "Fórmulas",
    formulasDesc: "Use funções e fórmulas para calcular dados.",
    data: "Dados",
    dataDesc: "Gerencie dados, incluindo importação, ordenação e filtros.",
    view: "Exibir",
    viewDesc: "Altere modos de visualização e o efeito de exibição.",
    others: "Outros",
    othersDesc: "Outras funções e configurações.",
    more: "Mais",
  },
  "shortcut-panel": { title: "Atalhos" },
  "common-edit": "Atalhos comuns de edição",
  "toggle-shortcut-panel": "Alternar painel de atalhos",
  textEditor: {
    formulaError: "Digite uma fórmula válida, como =SOMA(A1)",
    rangeError: "Digite um intervalo válido, como A1:B10",
  },
  "global-shortcut": "Atalho global",
  "zoom-slider": { resetTo: "Redefinir para" },
};
